i18n提出
maeda-seina/fjord-books_app pull request #1
Opened 2021-03-29 03:47 UTC by maeda-seina

添削お願いします！

2021-04-04 01:18 UTC, u1tnk requested changes

2021-04-04 01:18 UTC, u1tnk commented on app/controllers/books_controller.rb
> +        format.html { redirect_to @book, notice: t('book_was_successfully_created') }
キー名は成功したときしか参照しないので successfullyは不要かなと思います。

2021-04-04 01:18 UTC, u1tnk commented on app/views/books/index.html.erb
> +      <th><%= t :Title %></th>
https://qiita.com/yshr04hrk/items/cb7b81c104321f660661

こちら確認して Model情報を使うようにしてください。

2021-04-04 09:24 UTC, maeda-seina commented on app/views/books/index.html.erb
> +      <th><%= t :Title %></th>
了解いたしました！
参考記事ありがとうございます！

2021-04-04 09:28 UTC, maeda-seina commented on app/controllers/books_controller.rb
> +        format.html { redirect_to @book, notice: t('book_was_successfully_created') }
了解です！

2021-04-05 02:04 UTC, u1tnk approved these changes

2021-04-11 23:31 UTC, merged