フォロー機能提出
maeda-seina/fjord-books_app pull request #6
Opened 2021-04-04 04:30 UTC by maeda-seina

添削お願いします！

2021-04-09 15:05 UTC, u1tnk requested changes
コメントしました！

2021-04-09 15:05 UTC, u1tnk commented on Gemfile
> +  gem 'better_errors'
便利gemが入ってますね！

2021-04-09 15:05 UTC, u1tnk commented on app/controllers/relationships_controller.rb
> +    flash[:notice] = 'ユーザーをフォローしました' if following.save
これだと saveに失敗したときはメッセージが無く、ただユーザ詳細に戻ってしまいますね。

基本的にここに来たら失敗しないのであれば `save!`にしてエラー画面にするべきで、validation errorが起きる想定ならエラーメッセージも必要だと思います。

2021-04-09 15:05 UTC, u1tnk commented on app/controllers/relationships_controller.rb
> +    following = current_user.unfollow(@user)
同上

2021-04-09 15:05 UTC, u1tnk commented on app/controllers/relationships_controller.rb
> +    redirect_to @user
flashでメッセージを渡していますが、 https://api.rubyonrails.org/v6.1.0/classes/ActionController/Redirecting.html#method-i-redirect_to と redirect_toの引数に渡す方が見やすいですね。

2021-04-09 15:05 UTC, u1tnk commented on app/controllers/relationships_controller.rb
> +    flash[:notice] = 'ユーザーをフォローしました' if following.save
また、 User#follow で createしているのにここで saveしてるの二重になっていると思います。

2021-04-09 15:05 UTC, u1tnk commented on db/migrate/20210403112254_create_relationships.rb
> +    create_table :relationships do |t|
中間テーブルに Relationと付けるのはあまり良くないですね。
名前があまりに抽象的です。 フォローの為の中間テーブルである事は名前で分かるようにした方が良いですね。
同様に名前が user/follow だと意味が揃っていないのが気になりますので考えてみてください。

2021-04-12 00:54 UTC, maeda-seina commented on app/controllers/relationships_controller.rb
> +    flash[:notice] = 'ユーザーをフォローしました' if following.save
了解です！
ありがとうございます！

2021-04-12 00:54 UTC, maeda-seina commented on app/controllers/relationships_controller.rb
> +    redirect_to @user
了解いたしました！

2021-04-12 01:13 UTC, maeda-seina commented on db/migrate/20210403112254_create_relationships.rb
> +    create_table :relationships do |t|
修正してみます！

2021-04-13 07:26 UTC, maeda-seina commented on db/migrate/20210403112254_create_relationships.rb
> +    create_table :relationships do |t|
修正してみましたので確認お願いします！

2021-04-13 13:34 UTC, u1tnk approved these changes

2021-04-14 01:24 UTC, merged