My testing
maeda-seina/fjord-books_app pull request #8
Opened 2021-04-17 03:59 UTC by maeda-seina

添削お願いいたします！

2021-04-22 01:12 UTC, komagata commented
My TestingではなくMy Testsとかの方が英語的にただしいかも？

2021-04-22 01:14 UTC, komagata requested changes

2021-04-22 01:14 UTC, komagata commented on test/fixtures/relationships.yml
> +# one:
基本的にgitで管理しているのでいつでも古い状態に戻せるため、コメントアウトして一時的に無効にしておくと言うのは必要ないです。

不要なファイル・コードは削除しちゃってください〜

2021-04-23 05:05 UTC, maeda-seina commented
> My TestingではなくMy Testsとかの方が英語的にただしいかも？

本当ですね😅修正します！！

2021-04-23 05:05 UTC, maeda-seina commented on test/fixtures/relationships.yml
> +# one:
了解いたしました！！

2021-04-23 16:19 UTC, komagata requested changes

2021-04-23 16:19 UTC, komagata commented on test/models/report_test.rb
> +    alice = User.new(email: 'alice@example.com', name: '')
aliceはfixtureの中にあるのでそれを使った方が良いかもです〜

2021-04-24 13:35 UTC, maeda-seina commented on test/models/report_test.rb
> +    alice = User.new(email: 'alice@example.com', name: '')
了解です！

2021-04-24 16:28 UTC, komagata requested changes

2021-04-24 16:28 UTC, komagata commented on test/models/report_test.rb
> +    bob = User.new(email: 'bob@example.com', name: '')
bobもよく出てきそうなのでfixtureで作ると良いかもです。

2021-04-25 04:45 UTC, maeda-seina commented on test/models/report_test.rb
> +    bob = User.new(email: 'bob@example.com', name: '')
了解です！
日報とユーザーのモデルテストに、aliceとbobを使用するよう修正しました！

あと、systemテストのbooks_test.rbで
`@book = books(:cherry_book)`としていましたが、
`@book`を使用しないため、`books(:cherry_book)`を`@book`に代入する記述は削除し、
`books(:cherry_book)`だけにしました。

2021-04-26 08:25 UTC, komagata requested changes

2021-04-26 08:25 UTC, komagata commented on test/models/report_test.rb
> +  end
```suggestion
  test '#editable' do
    assert eports(:alice_report).editable?(users(:alice))
    assert_not eports(:alice_report).editable?(users(:bob))
  end
```

一旦一時変数に入れなくても名前が自明なのでこういう感じでもいいかもと思いました。

2021-04-29 08:56 UTC, maeda-seina commented on test/models/report_test.rb
> +  end
なるほどです！
やってみたところ、とても短くなりました！😄

2021-05-01 12:47 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-05-02 00:03 UTC, merged